# Generated by Django 2.1.1 on 2018-12-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('date_created', models.DateField()),
                ('date_last_edited', models.DateField()),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('compid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('game_type', models.TextField()),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('made_by', models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamedb.Company')),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gname', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('pname', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'platform',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_acct',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='gid',
            field=models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='gamedb.Game'),
        ),
    ]
